# Generated by Django 5.1.7 on 2025-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения привычки")),
                ("action", models.CharField(max_length=50, verbose_name="Действие")),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        help_text="Периодичность в днях",
                        verbose_name="Периодичность привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Награда"
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        verbose_name="Время на выполнение в секундах"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Признак публичности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
